---
gmail: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
facebook: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
github: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
paypal: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
amazon_aws: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
stackexchange: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
gravatar: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
velocityresidence-admin: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
heroku: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
eclipse-secure-store: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
minecraft-tom: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 8
  suffix: 
newegg.ca: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
mastercard-securecode: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  length: 12
  suffix: 
linkedin: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
irc: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
watiam: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
quikasyst-aws: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
quikasyst-appleid: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
quikasyst-godaddy-webmail: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
arch-wiki: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
td-security-question: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  length: 16
  suffix: ''
td-password: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  length: 8
  suffix: ''
encircle-googleapps: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
encircle-android-key: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
kerbal-space-program: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
encircle-webserver-root-key: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
encircle-chef-ampq-user: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz
  length: 16
  suffix: ''
encircle-chef-webui: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
wolfram-id: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
encircle-desk-mailbox: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
encircle-tumblr: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
virtex: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
localbitcoins: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
blackberry-signing-key: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789abcdefghijklmnopqrstuvwxyz
  length: 10
  suffix: ''
rbc-banking: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 32
  suffix: ''
rbc-security1: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
rbc-security2: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
rbc-security3: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
reddit-ninja_parade: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
simpletax: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
warranty-life: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
snapnames-cbiocca: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
bitcointalk2: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
bitcoin-dev-list: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
reason: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
postmark: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
yelp: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 14
  suffix: ''
textsecure: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
encirclephabricator: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
rsi-cbiocca: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
encircle-testflight: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
enercare: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
havelock: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
bitcoin-foundation: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
bitcoin-foundation-forum: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
android-pin: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789
  length: 12
  suffix: ''
23andme: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
23andme-security-question: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  length: 12
  suffix: ''
encircle-cnet: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: "-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"
  length: 12
  suffix: ''
gameolith: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
no-ip-cbiocca: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
trezor-account: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
overstock: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
humblebundle: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
xapo.com: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789
  length: 4
  suffix: ''
projecteuler: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz
  length: 15
  suffix: ''
keybase.io: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
encircle-stripe: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
ups: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
encircle-crashlytics: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
coinbase: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
encircle-hootsuite: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
playdiplomacy.com: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
encircle-softlayer: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: "!#$%&()*+,-./0123456789=?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_abcdefghijklmnopqrstuvwxyz{|}~"
  length: 16
  suffix: ''
ticketfi: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
liberty.me: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
