---
facebook: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
github: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
paypal: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
amazon_aws: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
exquisine-appleid: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: "-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"
  length: 10
  suffix: 
glados-gmail: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
stackexchange: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
gravatar: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
croutonlabs-mysql-root: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
ubuntu-one: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
velocityresidence-admin: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
xerox-gmail: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
heroku: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
beanstream-exquisine-christophe: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
polychart: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
ni.com: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
eclipse-secure-store: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
croutonlabs-bot-email: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
minecraft-tom: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 8
  suffix: 
newegg.ca: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
bufferbox: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: 
mastercard-securecode: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  length: 12
  suffix: 
linkedin: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
irc: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
watiam: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
quikasyst-aws: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
bookneto: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
twitter-eraseme: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
sloshtag: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
quikasyst-appleid: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
quikasyst-godaddy-webmail: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
arch-wiki: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
td-security-question: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  length: 16
  suffix: ''
td-password: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  length: 8
  suffix: ''
encircle-googleapps: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
encircle-android-key: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
kerbal-space-program: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
encircle-webserver-root-key: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
encircle-chef-ampq-user: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz
  length: 16
  suffix: ''
encircle-chef-webui: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
wolfram-id: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
encircle-vidyard: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
mtgox: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
coinworker: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
bloomfire: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
encircle-desk-mailbox: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
encircle-tumblr: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
encircle-mailchimp: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
virtex: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
btc-guild: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
localbitcoins: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
blackberry-signing-key: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789abcdefghijklmnopqrstuvwxyz
  length: 10
  suffix: ''
rbc-banking: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 32
  suffix: ''
rbc-security1: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
rbc-security2: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
rbc-security3: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
connestoga-college: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
connestoga-security-question: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
reddit-ninja_parade: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
simpletax: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
warranty-life: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
snapnames-cbiocca: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
bitcointalk2: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
bitcoin-dev-list: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
reason: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
postmark: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
libertybit: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
yelp: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 14
  suffix: ''
textsecure: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
encirclephabricator: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
rsi-cbiocca: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
encircle-testflight: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 15
  suffix: ''
enercare: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
havelock: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
bitcoin-foundation: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
bitcoin-foundation-forum: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
android-pin: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789
  length: 12
  suffix: ''
23andme: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
23andme-security-question: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  length: 12
  suffix: ''
encircle-cnet: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: "-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"
  length: 12
  suffix: ''
gameolith: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 12
  suffix: ''
no-ip-cbiocca: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 10
  suffix: ''
trezor-account: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
cointrader.net: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
overstock: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
humblebundle: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
xapo.com: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789
  length: 4
  suffix: ''
projecteuler: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz
  length: 15
  suffix: ''
keybase.io: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
encircle-stripe: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 20
  suffix: ''
ups: !ruby/object:PasswordRepo::PasswordGenerator
  character_set: '!"#$%&''()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~'
  length: 16
  suffix: ''
